### ISSUE TITLE
How to test the web site/application support how many concurrent users?

### ISSUE THREAD

**Issue by viphuangwei** [amejiarosario/ama#5]
Hi Adrian,
I saw your blog about "How to scale a Nodejs app based on number of users", it's very helpful to us, Thank you a lot. one question i want to ask is "How to test the web site/application support how many concurrent users?" could you please give us some idea or some good tool for that?

Best Regards,
Wei.

**Comment by amejiarosario** [comment]
Hi Wei,

I'm glad you liked it. 

There are many tools to test concurrency, I have used:
- [httperf](https://sourceforge.net/projects/httperf/)
- [ab](http://httpd.apache.org/docs/2.4/programs/ab.html) (Apache Bench)
- [gatling](http://gatling.io)

On the most useful metrics for web performance is the 95th percentile. Use that instead of averages. 

Let's say you test with 100 concurrent users. Each (test) user will have a different response time. If you sort all the response times in order and take the one in the place 95th. That's the  **95th percentile**.
